# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/demix',
                'doc_host': 'https://slegroux.github.io',
                'git_url': 'https://github.com/slegroux/demix',
                'lib_path': 'demix'},
  'syms': {'demix.core': {'demix.core.foo': ('core.html#foo', 'demix/core.py')}}}
